apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-serv
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-serv
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: api-serv
    spec:
      containers:
        - name: api-serv
          image: marvin666/api-bootcamp-produto:v8
          ports: 
          - containerPort: 8080
          env:
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-serv
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  type: LoadBalancer
